### PR TITLE
updated devise for first_name and last_name

### PR DESCRIPTION
**Pull request by linqiu**
Hey,
- edited the registration/new form (typo with :email twice)
- fixed the profile bar at the top right nav by adding the - in front of the IF statement for current_user? 
- fixed route of home#index
- i commented out :confirmable! (because the information for mailer config isn't there)

### CODE REVIEW

**Comment by karlhigley** [comment]
The Gemfile has been changed back to use postgres instead of sqlite, but the database.yml is still configured to use sqlite instead of postgres.  Postgres can be kind of a headache to install and configure if you're new to databases, so maybe sqlite would be better for this project?  Either way, the Gemfile and database.yml should match before this gets merged.

**Comment by jkeam** [comment]
Postgres is good to use especially since we are deploying to heroku.  My
vote is for both to be postgres :)

**Comment by linqiu** [comment]
yeah, my Bs for still having database.yml pointing to sqlite. heroku strips production and puts it on postgres anyways. i've fixed that issue.

**Comment by psteininger** [comment]
I got some free time tonight. I will pull this in once I update the gems and fix the jquery UI debacle (my fault for trying to remove it :-)

**Comment by psteininger** [comment]
I meant - my fault for trying to make it work w/o a gem (I saw jQuery UI bundled with jQuery-rails, but it does not have the theme and is slightly out of date)

**Pull request merged**
