### PR TITLE
Switched database from Postgres to SQLite.

### PR DESCRIPTION
**Pull request by karlhigley**
(In order for contributors to be able to easily set up the application on their machines.)

### CODE REVIEW

**Comment by districtem** [comment]
@psteininger we needed to update the DB from Postgres as many potential contributors were getting stuck in configuration and not being able to contribute.

**Comment by psteininger** [comment]
Hey guys, 

This is not the right way to handle this. It sets the wrong precedent.
The database should be the same in local, test and production environments. This prevents a ton of issues. Namely the issue of boolean column in SQLite in our case. I saw someone changing a view in order to make logic dependent on boolean being boolean not integer. Also changing this around will break things for others. Some people don't have sqlite gem installed. Overall, any changes to the database.yml are discouraged.

Please reverse it to the original. If anyone has issues with Postgres, they should change the file locally and not check it in. They can stash things when rebasing and omit in commits altogether. Also everyone should have their own fork from which to work, and they should only commit/request pull when the work is on a feature or confirmed bug. I saw commits recently to things that are not related to that.

We opened up this project in a very unbaked state. There is a lot to build and complete. I plan on continuing work on this and giving more direction in free time. 

I appreciate your understanding on this issue,

Best,

Piotr

**Comment by districtem** [comment]
Piotr,

Thanks for the reply.  This clarification greatly helps.

Just explaining what happened today to lead to changing the dev/test/production DBs:
I attended RubyRetrocession and volunteered RGManager for newbies to work on as an open source project as we already had a base and need some features/issues added.

Everyone forked/cloned RGManager to their machine but then ran into a host of issues configuring Postgres on their machine.  The issues ran into being able to configure Postgres under the rgmanager user, although I think the rgmanager user is better/more secure than the postgres user.  We then decided (and this is my fault and I thought the production env. was elsewhere as the original main repo only had a Dev and Test DB env configured in database.yml) that it would be okay and better to update the app to use SQLite instead of Postgres as that was much easier for everyone to set-up and start running the app locally.

I can definitely re-update the project to reflect the fact that postgres is needed/required and the specific DB's should be created (rgmanager_development and rgmanager_test and a separate user rgmanager).  
To do this though, I do have a couple questions:
1) what is the explicit reason to keep dev as Postgres? (I'm assuming because the code deploys directly to heroku and as you said there is specific Postgres code involved with that)
2) in order for people to configure the DB I want to include the correct documentation for Postgres.  To config the DB on my machine I created the rgmanager_development and rgmanager_test DBs, rgmanager PSQL user, and then created an actual user in rails console with admin properties.  Is this exact configuration required for every potential contributor?  I just want to make sure there is clear documentation for how to create the correct DB's and user cases in the app.
3) Jim brought up creating a "set-up" script for people to run to configure things for them.  I am not opposed to looking into this…this could also potentially let people set up their own local DB's as long as they remember to not push the database.yml code when committing.  As I said, not opposed to figuring this out…but will prolong being able to contribute as I want to get this right.

My gut feelings are to just reset the DB's to postgres and include very specific documentation for configuring the DB environments and not doing the "set-up" script.

Thanks so much for the feedback, sorry for any headache this caused!!!

Emily

about.com/emilywilliamson
@DistrictEm1
540.616.8336

**Comment by psteininger** [comment]
Hey Emily,

You guys are doing great. The group is mostly novices, and the project is
in a bit of disarray, because of me. I could have made it more of  priority
before I left.
So there is nothing unusual about some early pains getting into the grind
of things.

I understand that it's not easy to get set up with postgres, especially on
windows. The quick fix is to run sqlite or mysql locally, which is not a
terrible thing to do, but comes with some potentially serious issues. In
case of SQLite, it simply does not support boolean type and in rails it's
creating a lot of problems. There is also the issue of not being able to
test things exactly how they run in production (i.e a bug in prod on PG may
not reproduce locally on another db). There are other issues, but these I
know first hand.

So the typical thing you'll see about postgres install, is that it uses the
default user and the default database. Well, everyone's usernames are
different . Some people work on multiple projects, where they need to be
stored in separate databases and best with separate users.

So I really like the idea of creating a "getting started" document. As time
goes by, I am positive that there will be more complex dependencies than
just the database. For example: SendGrid, Redis, Amazon S3, etc. So there
will no doubt be more complexity in setup.

Would you want to take on the task of creating a wiki page or would you
like me to start it?

Thanks for rallying up the community and keeping focus on this project. Liz
and I really appreciate it. Hopefully we'll be able to contribute more soon
:).

Best,

Piotr

On Sun, Feb 17, 2013 at 4:49 AM, Emily Williamson
notifications@github.comwrote:

> Piotr,
> 
> Thanks for the reply. This clarification greatly helps.
> 
> Just explaining what happened today to lead to changing the
> dev/test/production DBs:
> I attended RubyRetrocession and volunteered RGManager for newbies to work
> on as an open source project as we already had a base and need some
> features/issues added.
> 
> Everyone forked/cloned RGManager to their machine but then ran into a host
> of issues configuring Postgres on their machine. The issues ran into being
> able to configure Postgres under the rgmanager user, although I think the
> rgmanager user is better/more secure than the postgres user. We then
> decided (and this is my fault and I thought the production env. was
> elsewhere as the original main repo only had a Dev and Test DB env
> configured in database.yml) that it would be okay and better to update the
> app to use SQLite instead of Postgres as that was much easier for everyone
> to set-up and start running the app locally.
> 
> I can definitely re-update the project to reflect the fact that postgres
> is needed/required and the specific DB's should be created
> (rgmanager_development and rgmanager_test and a separate user rgmanager).
> To do this though, I do have a couple questions:
> 1) what is the explicit reason to keep dev as Postgres? (I'm assuming
> because the code deploys directly to heroku and as you said there is
> specific Postgres code involved with that)
> 2) in order for people to configure the DB I want to include the correct
> documentation for Postgres. To config the DB on my machine I created the
> rgmanager_development and rgmanager_test DBs, rgmanager PSQL user, and then
> created an actual user in rails console with admin properties. Is this
> exact configuration required for every potential contributor? I just want
> to make sure there is clear documentation for how to create the correct
> DB's and user cases in the app.
> 3) Jim brought up creating a "set-up" script for people to run to
> configure things for them. I am not opposed to looking into this…this could
> also potentially let people set up their own local DB's as long as they
> remember to not push the database.yml code when committing. As I said, not
> opposed to figuring this out…but will prolong being able to contribute as I
> want to get this right.
> 
> My gut feelings are to just reset the DB's to postgres and include very
> specific documentation for configuring the DB environments and not doing
> the "set-up" script.
> 
> Thanks so much for the feedback, sorry for any headache this caused!!!
> 
> Emily
> 
> about.com/emilywilliamson
> @DistrictEm1
> 540.616.8336
> 
> On Feb 16, 2013, at 5:33 PM, Piotr Steininger notifications@github.com
> wrote:
> 
> > Hey guys,
> > 
> > This is not the right way to handle this. It sets the wrong precedent.
> > The database should be the same in local, test and production
> > environments. This prevents a ton of issues. Namely the issue of boolean
> > column in SQLite in our case. I saw someone changing a view in order to
> > make logic dependent on boolean being boolean not integer. Also changing
> > this around will break things for others. Some people don't have sqlite gem
> > installed. Overall, any changes to the database.yml are discouraged.
> > 
> > Please reverse it to the original. If anyone has issues with Postgres,
> > they should change the file locally and not check it in. They can stash
> > things when rebasing and omit in commits altogether. Also everyone should
> > have their own fork from which to work, and they should only commit/request
> > pull when the work is on a feature or confirmed bug. I saw commits recently
> > to things that are not related to that.
> > 
> > We opened up this project in a very unbaked state. There is a lot to
> > build and complete. I plan on continuing work on this and giving more
> > direction in free time.
> > 
> > I appreciate your understanding on this issue,
> > 
> > Best,
> > 
> > Piotr
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tapangi/rgmanager/pull/17#issuecomment-13680274.

## 

Met vriendelijke groet,

*Code4EU Amsterdam fellows *
Piotr Steininger  06 2847 2484  @polishprince
Ohyoon Kwon  06 2815 7413  @ohyoonkwn

## Giovanni Maggini  06 8131 9196  @maggix

See our schedulehttps://www.google.com/calendar/embed?src=nq2qcraf1urnkg6lno76dudtfk@group.calendar.google.com&ctz=Europe/Amsterdam

**Comment by districtem** [comment]
Hey Piotr,

Awesome, that all sounds good.  If you can start the wiki page that would be best.  I am not familiar with creating wiki pages, but if you get one up I can maintain it as issues arise.

In the meantime I will go back in and update the databases to Postgres with the rgmanager user, etc, and I will add instructions for DB configuration to the database.yml file with links in the README.

Thanks for all the help!!

Emily

**Pull request merged**
